import { Routes } from '@angular/router';
import { PhoneComponent } from './screens/phone.component'
import { OtpComponent } from './screens/otp.component';
import { CategoryComponent } from './screens/category.component';
import { UsernameComponent } from './screens/username.component';
import { EmailComponent } from './screens/email.component';
import { AgeComponent } from './screens/age.component';
import { HeightComponent } from './screens/height.component';
import { GenderComponent } from './screens/gender.component';
import { ActivityComponent } from './screens/activity.component';
import { UserImageComponent } from './screens/user-image.component';
import { FinishComponent } from './screens/finish.component';
import { GymPlansComponent } from './screens/gym-plans.component';
import { LoginComponent } from './screens/login.component';
import { PasswordComponent } from './screens/password.component';
import { GymInfoComponent } from './screens/gym-info.component';
import { TrainerInfoComponent } from './screens/trainer-info.component';
import { GymWebsiteComponent } from './screens/gym-website.component';
import { GymSocialMediaComponent } from './screens/gym-social-media.component';

export const SIGNUP_ROUTES: Routes = [
  { path: 'phone', component: PhoneComponent },
  { path: 'otp', component: OtpComponent },
  { path: 'category', component: CategoryComponent },
  { path: 'username', component: UsernameComponent },
  { path: 'email', component: EmailComponent },
  { path: 'gym-plans', component: GymPlansComponent },
  { path: 'password', component: PasswordComponent },
  { path: 'login', component: LoginComponent },
  { path: 'gym-info', component: GymInfoComponent },
  { path: 'trainer-info', component: TrainerInfoComponent },
  { path: 'gym-website', component: GymWebsiteComponent },
  { path: 'gym-social-media', component: GymSocialMediaComponent },
  { path: 'age', component: AgeComponent },
  { path: 'gender', component: GenderComponent },
  { path: 'height', component: HeightComponent },
  { path: 'activity', component: ActivityComponent },
  { path: 'image', component: UserImageComponent },
  { path: 'finish', component: FinishComponent },
  { path: '', pathMatch: 'full', redirectTo: 'phone' },
];
